[package]
name = "poll_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.10.3"
borsh-derive = "1.2.0"
solana-program = "1.17.5"

[lib]
crate-type = ["cdylib"]
